### ISSUE TITLE
Improve output

### ISSUE THREAD

**Issue by potherca** [WouterHendriks/wh-creator#3]
In it's current state, (error) messaging and output from command run by this script are somewhat garbled.
It is hard to distinguish between which information _is_ and which information is not relevant. Also, it is hard to easily distinguish between info and error output. 

This should be amended:

- [X] Checks should be added
 - [X] Does the `wh` command exist? (see #8, fixed in 664ad7a)
 - [X] Is WebHare running? (fixed in 1798d49)
 - [x] Does the input match a valid constraint? (fixed in c78dfec)
- [x] The output should be improved
 - [x] Clean up info and output message (fixed in 664ad7a)
 - [X] Make errors more clear (fixed in 664ad7a)

**Comment by WouterHendriks** [comment]
At least the output is improved by 4a0a515.

**Comment by potherca** [comment]
This issue should be resolved when #9 is merged.
